name: deploy
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  deploy:
    runs-on: [self-hosted, puzzu]
    steps:
      - uses: actions/checkout@v4
      - env:
          KUBECONFIG: /home/runner/.kube/config
        run: ansible-playbook ci/ansible/deploy-puzzu.yml
